import { MAX_CU, MAX_DATA, canonical, type Features } from './message.js';
export const NUMERICAL=['signature_count','account_count','signer_count','writable_count','instruction_count','total_instruction_data_bytes','lookup_table_count','lookup_writable_count','lookup_readonly_count','serialized_size','requested_heap_bytes'] as const;
type Range={minimum:number|null;maximum:number|null;missing_seen:boolean};
export type ResourcePolicy={quantile:number;compute_margin_bps:number;data_margin_bps:number;compute_rounding:number;data_rounding:number;min_samples:number;min_calibration_samples:number;max_joint_underestimation_rate:number;max_age_slots:string;near_limit_ratio:number;calibration_fraction:number;independence_window_slots:number;allow_v1:boolean};
export type ResourceStats={train_count:number;calibration_count:number;training_max_slot:string;calibration_min_slot:string|null;max_slot:string;quantile_compute_units:number;quantile_loaded_accounts_bytes:number;compute_unit_limit:number;loaded_accounts_data_size_limit:number;calibration_compute_exceedances:number;calibration_data_exceedances:number;calibration_joint_exceedances:number;calibration_upper_bound:number|null;numerical_ranges:Record<typeof NUMERICAL[number],Range>;instruction_data_length_ranges:Range[];program_ids:string[];version:'legacy'|0|1};
export type ResourceArtifact={artifact_version:'cu-pilot-resources-v1';context:string;source:'historical'|'simulation'|'synthetic';label_source:'historical'|'simulation'|'synthetic'|null;evidence_origin:'synthetic'|'local-runtime'|'live-simulation'|'historical-execution'|null;max_slot:string;training_max_slot:string;calibration_min_slot:string|null;policy:ResourcePolicy;patterns:Record<string,ResourceStats>;diagnostics:Record<string,number>};
export type Prediction={pattern_id:string;compute_unit_limit:number|null;loaded_accounts_data_size_limit:number|null;simulation_recommended:boolean;reason:string;sample_count:number;calibration_count:number;calibration_underestimation_upper_bound:number|null};
export function slot(value:unknown):bigint {if(typeof value!=='string'||! /^(0|[1-9][0-9]*)$/.test(value))throw new Error('invalid_exact_slot');const n=BigInt(value);if(n>=2n**64n)throw new Error('invalid_exact_slot');return n;}
function uint(value:unknown,max=Number.MAX_SAFE_INTEGER):asserts value is number {if(typeof value!=='number'||!Number.isSafeInteger(value)||value<0||value>max)throw new Error('invalid_integer');}
function probability(value:unknown,zero=false,one=false):asserts value is number {if(typeof value!=='number'||!Number.isFinite(value)||(zero?value<0:value<=0)||(one?value>1:value>=1))throw new Error('invalid_probability');}
function object(value:unknown):asserts value is Record<string,unknown>{if(value===null||typeof value!=='object'||Array.isArray(value))throw new Error('invalid_artifact_object');}
function keys(value:object,names:string[]){object(value);if(canonical(Object.keys(value).sort())!==canonical(names.sort()))throw new Error('incompatible_artifact_fields');}
export function roundedLimit(value:number,marginBps:number,step:number):number {uint(value);uint(marginBps);uint(step);if(!step)throw new Error('invalid_rounding');const denominator=10000n*BigInt(step);const n=((BigInt(value)*(10000n+BigInt(marginBps))+denominator-1n)/denominator)*BigInt(step);const rounded=n<BigInt(step)?BigInt(step):n;if(rounded>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('inexact_resource_limit');return Number(rounded);}
function range(r:Range){keys(r,['minimum','maximum','missing_seen']);if(typeof r.missing_seen!=='boolean')throw new Error('invalid_range');if(r.minimum===null||r.maximum===null){if(r.minimum!==null||r.maximum!==null||!r.missing_seen)throw new Error('invalid_range');}else{uint(r.minimum,2**32-1);uint(r.maximum,2**32-1);if(r.minimum>r.maximum)throw new Error('invalid_range');}}
export function wilsonUpper(failures:number,count:number){uint(failures);uint(count);if(!count||failures>count)throw new Error('invalid_joint_counts');const z=1.6448536269514722;const p=failures/count;return (p+z*z/(2*count)+z*Math.sqrt(p*(1-p)/count+z*z/(4*count*count)))/(1+z*z/count);}
/** Strict portable JSON validator. CU-only and unknown formats never qualify. */
export function loadArtifact(value:unknown):ResourceArtifact {
  const a=structuredClone(value) as ResourceArtifact;
  if(!a||typeof a!=='object'||a.artifact_version!=='cu-pilot-resources-v1')throw new Error('incompatible_artifact');
  keys(a,['artifact_version','context','source','label_source','evidence_origin','max_slot','training_max_slot','calibration_min_slot','policy','patterns','diagnostics']);
  if(a.label_source!==null&&!['historical','simulation','synthetic'].includes(a.label_source))throw new Error('invalid_provenance');
  if(a.evidence_origin!==null&&!['synthetic','local-runtime','live-simulation','historical-execution'].includes(a.evidence_origin))throw new Error('invalid_provenance');
  if(typeof a.context!=='string'||!a.context||!['historical','simulation','synthetic'].includes(a.source))throw new Error('invalid_artifact_context');
  if(a.evidence_origin==='synthetic'&&a.source!=='synthetic'||a.source!=='synthetic'&&a.label_source!==null&&a.label_source!==a.source)throw new Error('invalid_provenance');
  const max=slot(a.max_slot),fit=slot(a.training_max_slot),cal=a.calibration_min_slot===null?null:slot(a.calibration_min_slot);if(fit>max||(cal!==null&&(cal<=fit||cal>max)))throw new Error('invalid_chronology');
  const p=a.policy;keys(p,['quantile','compute_margin_bps','data_margin_bps','compute_rounding','data_rounding','min_samples','min_calibration_samples','max_joint_underestimation_rate','max_age_slots','near_limit_ratio','calibration_fraction','independence_window_slots','allow_v1']);
  probability(p.quantile,false,true);probability(p.max_joint_underestimation_rate);probability(p.near_limit_ratio,false,true);probability(p.calibration_fraction);slot(p.max_age_slots);
  for(const name of ['compute_margin_bps','data_margin_bps','compute_rounding','data_rounding','min_samples','min_calibration_samples','independence_window_slots'] as const)uint(p[name]);
  if(p.compute_margin_bps>100000||p.data_margin_bps>100000||!p.compute_rounding||p.compute_rounding>MAX_CU||!p.data_rounding||p.data_rounding>MAX_DATA||!p.min_samples||!p.min_calibration_samples||!p.independence_window_slots||p.independence_window_slots>2**32-1||typeof p.allow_v1!=='boolean')throw new Error('invalid_policy');
  object(a.patterns);for(const [id,s] of Object.entries(a.patterns)){
    keys(s,['train_count','calibration_count','training_max_slot','calibration_min_slot','max_slot','quantile_compute_units','quantile_loaded_accounts_bytes','compute_unit_limit','loaded_accounts_data_size_limit','calibration_compute_exceedances','calibration_data_exceedances','calibration_joint_exceedances','calibration_upper_bound','numerical_ranges','instruction_data_length_ranges','program_ids','version']);
    if(!id||!['legacy',0,1].includes(s.version)||!Array.isArray(s.program_ids)||!s.program_ids.length||s.program_ids.some(v=>typeof v!=='string'||!v))throw new Error('invalid_profile');
    for(const name of ['train_count','calibration_count','quantile_compute_units','quantile_loaded_accounts_bytes','compute_unit_limit','loaded_accounts_data_size_limit','calibration_compute_exceedances','calibration_data_exceedances','calibration_joint_exceedances'] as const)uint(s[name]);
    if(!s.train_count||s.quantile_compute_units>MAX_CU||s.quantile_loaded_accounts_bytes>MAX_DATA||s.compute_unit_limit!==roundedLimit(s.quantile_compute_units,p.compute_margin_bps,p.compute_rounding)||s.loaded_accounts_data_size_limit!==roundedLimit(s.quantile_loaded_accounts_bytes,p.data_margin_bps,p.data_rounding))throw new Error('invalid_profile_limits');
    const sf=slot(s.training_max_slot),sm=slot(s.max_slot),sc=s.calibration_min_slot===null?null:slot(s.calibration_min_slot);
    if(sf>fit||sm>max||sm<sf||(sc!==null&&(cal===null||sc<cal||sc<=sf||sc>sm||sf/BigInt(p.independence_window_slots)>=sc/BigInt(p.independence_window_slots))))throw new Error('invalid_profile_chronology');
    if(Math.max(s.calibration_compute_exceedances,s.calibration_data_exceedances)>s.calibration_joint_exceedances||s.calibration_joint_exceedances>Math.min(s.calibration_count,s.calibration_compute_exceedances+s.calibration_data_exceedances))throw new Error('invalid_joint_counts');
    if(s.calibration_count){const expected=wilsonUpper(s.calibration_joint_exceedances,s.calibration_count),bound=s.calibration_upper_bound;if(sc===null||typeof bound!=='number'||!Number.isFinite(bound)||bound<0||bound>1||Math.abs(bound-expected)>1e-12*Math.max(Math.abs(bound),Math.abs(expected)))throw new Error('invalid_joint_bound');}else if(sc!==null||s.calibration_upper_bound!==null)throw new Error('invalid_joint_bound');
    keys(s.numerical_ranges,[...NUMERICAL]);Object.values(s.numerical_ranges).forEach(range);if(!Array.isArray(s.instruction_data_length_ranges)||s.instruction_data_length_ranges.length!==s.program_ids.length)throw new Error('invalid_shape_ranges');s.instruction_data_length_ranges.forEach(range);
  }
  keys(a.diagnostics,['input_count','duplicate_count','failed_count','missing_compute_count','missing_data_count','invalid_label_count','unsafe_feature_count','paired_usable_count','calibration_only_pattern_count','ineligible_calibration_count']);Object.values(a.diagnostics).forEach(v=>uint(v));return a;
}
function contains(r:Range,n:number|null){return n===null?r.missing_seen:r.minimum!==null&&r.maximum!==null&&n>=r.minimum&&n<=r.maximum;}
export function predictResources(a:ResourceArtifact,f:Features,context:string,currentSlot:bigint):Prediction {
  if(typeof currentSlot!=='bigint'||currentSlot<0n||currentSlot>=2n**64n)throw new Error('invalid_current_slot');
  const p=a.policy,s=Object.hasOwn(a.patterns,f.pattern_id)?a.patterns[f.pattern_id]:undefined;let reason:string|null=null;
  if(context!==a.context)reason='context_mismatch';else if(currentSlot<slot(a.max_slot))reason='backwards_slot';else if(f.version===1&&!p.allow_v1)reason='unsupported_version';else if(f.risk_flags.length)reason='risky_features';
  else if([...NUMERICAL,'requested_compute_units','requested_loaded_accounts_bytes'].some(k=>{const value=f[k as keyof Features];return value!==null&&(!Number.isSafeInteger(value)||(value as number)<0);})||f.account_count<1||f.account_count>256||f.signature_count<1||f.signer_count!==f.signature_count||f.signer_count>f.account_count||f.writable_count>f.account_count||f.instruction_count<1||f.instruction_count!==f.program_ids.length||f.instruction_count!==f.instruction_data_lengths.length||f.instruction_data_lengths.some(n=>!Number.isSafeInteger(n)||n<0)||f.instruction_data_lengths.reduce((x,y)=>x+y,0)!==f.total_instruction_data_bytes||f.lookup_writable_count+f.lookup_readonly_count>f.account_count||!f.pattern_id||f.program_ids.some(p=>!p))reason='incomplete_features';
  else if(f.requested_compute_units===null)reason='missing_compute_limit';else if(!Number.isSafeInteger(f.requested_compute_units)||f.requested_compute_units<=0||f.requested_compute_units>MAX_CU)reason='invalid_compute_budget';else if(f.requested_loaded_accounts_bytes===null)reason='missing_loaded_accounts_limit';else if(!Number.isSafeInteger(f.requested_loaded_accounts_bytes)||f.requested_loaded_accounts_bytes<=0||f.requested_loaded_accounts_bytes>MAX_DATA)reason='invalid_loaded_accounts_budget';else if(f.requested_heap_bytes!==null&&(f.requested_heap_bytes<32768||f.requested_heap_bytes>262144||f.requested_heap_bytes%1024))reason='invalid_heap_budget';
  else if(!s)reason='unknown_pattern';else if(currentSlot-slot(s.max_slot)>slot(p.max_age_slots))reason='stale_pattern';else if(f.version!==s.version||canonical(f.program_ids)!==canonical(s.program_ids)||f.instruction_data_lengths.length!==s.instruction_data_length_ranges.length)reason='shape_mismatch';else if(NUMERICAL.some(k=>!contains(s.numerical_ranges[k],f[k]))||s.instruction_data_length_ranges.some((r,i)=>!contains(r,f.instruction_data_lengths[i]!)))reason='out_of_distribution';else if(s.train_count<p.min_samples)reason='insufficient_training';else if(s.calibration_count<p.min_calibration_samples)reason='insufficient_calibration';else if(s.calibration_upper_bound===null||s.calibration_upper_bound>p.max_joint_underestimation_rate)reason='joint_calibration_risk';
  if(!reason&&s){for(const [name,value,cap] of [['compute',s.compute_unit_limit,MAX_CU],['loaded_accounts',s.loaded_accounts_data_size_limit,MAX_DATA]] as const){if(value>=cap){reason=`hard_${name}_limit`;break;}if(value>=cap*p.near_limit_ratio){reason=`near_${name}_limit`;break;}}}
  return {pattern_id:f.pattern_id,compute_unit_limit:!reason&&s?s.compute_unit_limit:null,loaded_accounts_data_size_limit:!reason&&s?s.loaded_accounts_data_size_limit:null,simulation_recommended:!!reason,reason:reason??'calibrated_resources',sample_count:s?.train_count??0,calibration_count:s?.calibration_count??0,calibration_underestimation_upper_bound:s?.calibration_upper_bound??null};
}

